### ISSUE TITLE
[Leave of other] Submit 1 time but 3 records were created

### ISSUE THREAD

**Issue by at-hantk** [AsianTechInc/AT-Portal#32]
Member registered Leave and submit it 1 time but 3 records were created.
See attach image.
![screen shot 2016-11-21 at 11 50 18](https://cloud.githubusercontent.com/assets/19488325/20471073/07529c90-afe1-11e6-9a50-918d2652b4c8.png)

**Comment by at-huett** [comment]
@at-hantk 
This is a bug before Nov 19th, we have found out and fixed.

Thanks so much.

**Comment by at-hantk** [comment]
Thanks ^^

**Comment by at-huydq** [comment]
beautifulthakn you miss HaOn Nov 21, 2016, at 2:12 PM, Nguyen Thi Khanh Ha <notifications@github.com> wrote:Thanks ^^—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AsianTechInc/AT-Portal","title":"AsianTechInc/AT-Portal","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/AsianTechInc/AT-Portal" class="">https://github.com/AsianTechInc/AT-Portal</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@at-hantk in #32: Thanks ^^"}],"action":{"name":"View Issue","url":"<a href="https://github.com/AsianTechInc/AT-Portal/issues/32#issuecomment-261860760" class="">https://github.com/AsianTechInc/AT-Portal/issues/32#issuecomment-261860760</a>"}}}

**Comment by at-huydq** [comment]
so should we close?
